<?php

namespace LittleApps\LittleJWT\Core\Concerns;

use LittleApps\LittleJWT\JWT\JsonWebToken;
use LittleApps\LittleJWT\Validation\Valid;
use LittleApps\LittleJWT\Validation\Validatables\StackValidatable;
use LittleApps\LittleJWT\Validation\ValidatedJsonWebToken;

trait HandlesValidate
{
    /**
     * Validates a JSON Web Token (JWT).
     *
     * @param JsonWebToken $jwt JWT instance to validate.
     * @param callable(\LittleApps\LittleJWT\Validation\Validator): void $callback Callable that receives Validator to set rules for JWT.
     * @return ValidatedJsonWebToken Validated JWT
     */
    public function validate(JsonWebToken $jwt, callable $callback = null)
    {
        $valid = $this->valid($jwt);

        if (is_callable($callback)) {
            $valid->passValidatorThru($callback);
        }

        // Run the JWT through a Valid instance and return the result.
        return new ValidatedJsonWebToken($jwt, $valid->passes());
    }

    /**
     * Validates a JSON Web Token.
     *
     * @param string $token
     * @param callable|null $callback
     * @return bool True if valid, false if not valid or token cannot be parsed.
     */
    public function validateToken(string $token, callable $callback = null)
    {
        $jwt = $this->parse($token);

        if (is_null($jwt)) {
            return false;
        }

        return $this->validate($jwt, $callback)->passes();
    }

    /**
     * Creates a Valid instance for validating a JWT.
     *
     * @param JsonWebToken $jwt JWT instance to validate (generated by parseToken() method)
     * @return Valid Valid instance (before validation is done)
     */
    public function valid(JsonWebToken $jwt)
    {
        $valid = new Valid($this->app, $jwt, $this->jwk);

        return $valid;
    }
}
