<?php

namespace LittleApps\LittleJWT\Testing;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Support\Traits\ForwardsCalls;

use LittleApps\LittleJWT\JWT\JWT;
use LittleApps\LittleJWT\LittleJWT as RealLittleJWT;
use LittleApps\LittleJWT\Validation\Valid;
use LittleApps\LittleJWT\Validation\Validatables\StackValidatable;
use LittleApps\LittleJWT\Validation\Validator;

/**
 * @mixin \LittleApps\LittleJWT\LittleJWT
 */
class LittleJWT
{
    use ForwardsCalls;

    protected $app;
    protected $littleJWT;

    public function __construct(Application $app, RealLittleJWT $littleJWT)
    {
        $this->app = $app;
        $this->littleJWT = $littleJWT;
    }

    /**
     * Creates a Valid instance for checking if a JWT is valid.
     *
     * @param JWT $jwt JWT instance to validate (generated by parseToken() method)
     * @return Valid Valid instance (before validation is done)
     */
    public function validJWT(JWT $jwt)
    {
        $valid = $this->littleJWT->validJWT($jwt);

        return new TestValid($this->app, $valid);
    }

    /**
     * Creates a Valid instance for checking if a JWT is valid.
     * The default callback is not added when testing.
     *
     * @param JWT $jwt
     * @param callable $callback Callback that recieves Validator to set checks for JWT.
     * @return Valid Valid instance (before validation is done)
     */
    public function validateJWT(JWT $jwt, callable $callback = null, $applyDefault = false)
    {
        $callbacks = [];

        // Default callback is not added because it expects Validator and not TestValidator
        if (! is_null($callback)) {
            array_push($callbacks, $callback);
        }

        $transformCallbacks = $this->createTransformCallback($callbacks);

        $validatable = new StackValidatable([$transformCallbacks]);

        return $this->littleJWT->validateJWT($jwt, [$validatable, 'validate'], $applyDefault);
    }

    /**
     * Parses a token as a JSON Web Token (JWT) and validates it.
     *
     * @param string $token The token to parse as a JWT and validate.
     * @param callable $callback Callable that receives TestValidator to set assertions for JWT.
     * @param bool $applyDefault If true, the default validatable is used first. (default: false)
     * @return bool True if token is valid.
     */
    public function validateToken(string $token, $callback = null, $applyDefault = false)
    {
        $jwt = $this->parseToken($token);

        return ! is_null($jwt) ? $this->validateJWT($jwt, $callback, $applyDefault) : false;
    }

    /**
     * Creates the callback which transforms a Validator to TestValidator and sends it through the callbacks.
     *
     * @param iterable $callbacks
     * @return \Closure
     */
    protected function createTransformCallback(iterable $callbacks)
    {
        return function (Validator $validator) use ($callbacks) {
            $testValidator = new TestValidator($this->app, $validator);

            foreach ($callbacks as $callback) {
                $callback($testValidator);
            }
        };
    }

    /**
     * Forwards method calls to the original LittleJWT instance.
     *
     * @param string $name Method name
     * @param array $parameters Method parameters
     * @return mixed
     */
    public function __call($name, $parameters)
    {
        return $this->forwardCallTo($this->littleJWT, $name, $parameters);
    }
}
