<?php

namespace LittleApps\LittleJWT\Testing;

use Illuminate\Support\Traits\ForwardsCalls;
use LittleApps\LittleJWT\Core\Handler;
use LittleApps\LittleJWT\JWT\JsonWebToken;
use LittleApps\LittleJWT\Validation\Valid;

class TestHandler extends Handler
{
    use ForwardsCalls;

    /**
     * Creates a Valid instance for checking if a JWT is valid.
     *
     * @param JsonWebToken $jwt JWT instance to validate (generated by parseToken() method)
     * @return Valid Valid instance (before validation is done)
     */
    public function valid(JsonWebToken $jwt)
    {
        return new TestValid($this->app, $jwt, $this->jwk);
    }
}
